on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.CRASH_ACTION }}"
        project-url: "https://github.com/kbrosnan/test-repo/projects/1"
        column-name: "Needs triage"
        label-name: "b:crash"
        columns-to-ignore: "*"
        
